### ISSUE TITLE
The dataset have problem after downloading (during exacting the data)

### ISSUE THREAD

**Issue by davidlee1102** [Surrey-EEEM066/EEEM066_Knife_Classification_code#3]
The problem when the dataset was zipped by OneDrive
After downloading, when the dataset is exacting, it has some errors
Solution: I think the dataset should be zipped before uploading to OneDrive
__ERROR INFO__

CorrelationId: dd2513ae-dfd6-4130-9a70-5fcc4d6bbdf0
UTC DateTime: 10/23/2023 21:15:13

The following files/folders have not been downloaded
0. EEEM066_Knife_Classification_dataset/Train/Schrade_IMP20CI_Imperial/IMG_4035.JPEG
1. EEEM066_Knife_Classification_dataset/Train/Schrade_IMP20CI_Imperial/IMG_4035_br.JPEG
2. EEEM066_Knife_Classification_dataset/Train/Schrade_IMP20CI_Imperial/IMG_4035_cn.JPEG
3. EEEM066_Knife_Classification_dataset/Train/Schrade_IMP20CI_Imperial/IMG_4035_xr.JPEG
4. EEEM066_Knife_Classification_dataset/Train/Schrade_IMP20CI_Imperial/IMG_4035_yr.JPEG
5. EEEM066_Knife_Classification_dataset/Train/Schrade_IMP20CI_Imperial/IMG_4036.JPEG
6. EEEM066_Knife_Classification_dataset/Train/Schrade_IMP20CI_Imperial/IMG_4036_br.JPEG
7. EEEM066_Knife_Classification_dataset/Train/Schrade_IMP20CI_Imperial/IMG_4036_cn.JPEG
8. EEEM066_Knife_Classification_dataset/Train/Schrade_IMP20CI_Imperial/IMG_4036_xr.JPEG
9. EEEM066_Knife_Classification_dataset/Train/Schrade_IMP20CI_Imperial/IMG_4036_yr.JPEG
10. EEEM066_Knife_Classification_dataset/Train/Schrade_Imperial_Stainless_3_Blade_Pocket_Knife
11. EEEM066_Knife_Classification_dataset/Train/Schrade_Small_Trapper_Knife_2_Blades
12. EEEM066_Knife_Classification_dataset/Train/Steel_File_Flat_For_Knife_Blade_Grinding
13. EEEM066_Knife_Classification_dataset/Train/US_Marine_Bowie_Style_Knife
14. EEEM066_Knife_Classification_dataset/Train/Victorinox_Classic_SD_7_Function_Swiss_Army_Knife
15. EEEM066_Knife_Classification_dataset/Train/Victorinox_Climber_14_Function_Swiss_Army_Knife
16. EEEM066_Knife_Classification_dataset/Train/Victorinox_Duke_of_Edingborough
17. EEEM066_Knife_Classification_dataset/Train/Victorinox_Huntsman_Camoflauge_15
18. EEEM066_Knife_Classification_dataset/Train/Victorinox_Spartan_Camouflage_12
19. EEEM066_Knife_Classification_dataset/Train/Woodcarving_Knife_Making_Kit
20. EEEM066_Knife_Classification_dataset/Train/Yellow_Rescue_Knife

**Comment by JosTheBossX** [comment]
Yes facing the same issue, tried to redownload, but still not working :(

**Comment by SyedSameedHusain** [comment]
The zip file is now present in https://surreyac-my.sharepoint.com/:f:/g/personal/sh0057_surrey_ac_uk/EmqNHsA6LLdNhmdR5VxAFA4Bi0It4-W44Wu_E46lwvbm0A?e=dJGQeG

**Comment by davidlee1102** [comment]
Thank you for helping us
